//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartridgeSolver
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CartridgeSolverDbDataConnection : DbContext
    {
        public CartridgeSolverDbDataConnection()
            : base("name=CartridgeSolverDbDataConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GenericCartridge> GenericCartridges { get; set; }
        public virtual DbSet<GenericBoardAtGenericCartridge> GenericBoardAtGenericCartridges { get; set; }
        public virtual DbSet<GenericBoardsData> GenericBoardsDatas { get; set; }
        public virtual DbSet<GenericCartridgesData> GenericCartridgesDatas { get; set; }
    }
}
