//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartridgeSolver
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenericCartridge
    {
        public int CartID { get; set; }
        public string Name { get; set; }
        public string ContainedBoards { get; set; }
        public decimal Length { get; set; }
        public bool NeedsCutting { get; set; }
        public int Serie { get; set; }
        public int InSerieID { get; set; }
    }
}
