//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_Data_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class assembly
    {
        public int id { get; set; }
        public bool isRootAssembly { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    }
}
