//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssemblyAtAssembly
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssemblyAtAssembly()
        {
            this.PartAtAssemblies = new HashSet<PartAtAssembly>();
        }
    
        public int id { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int AssemblyID { get; set; }
        public int FixtureID { get; set; }
    
        public virtual Assembly ToAssembly { get; set; }
        public virtual Assembly ToParent { get; set; }
        public virtual Fixture Fixture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartAtAssembly> PartAtAssemblies { get; set; }
    }
}
