//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MANAGER
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AXIS_AutomationEntities : DbContext
    {
        public AXIS_AutomationEntities()
            : base("name=AXIS_AutomationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assembly> Assemblies { get; set; }
        public virtual DbSet<AssemblyAtAssembly> AssemblyAtAssemblies { get; set; }
        public virtual DbSet<AssemblyType> AssemblyTypes { get; set; }
        public virtual DbSet<AssemblyView> AssemblyViews { get; set; }
        public virtual DbSet<PartAtAssembly> PartAtAssemblies { get; set; }
        public virtual DbSet<PartType> PartTypes { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<Fixture> Fixtures { get; set; }
        public virtual DbSet<AssemblyTypeAtAssembly> AssemblyTypeAtAssemblies { get; set; }
    }
}
