//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssemblyView
    {
        public int id { get; set; }
        public string AssemblyName { get; set; }
        public Nullable<int> AssemblyTypeID { get; set; }
        public string AssemblyTypeName { get; set; }
        public Nullable<int> AssyAtAssyID { get; set; }
        public Nullable<int> ParentIDAtAssyAtAssy { get; set; }
        public Nullable<int> AssemblyIDAtAssyAtAssy { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
