//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssemblyAtAssembly
    {
        public int id { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int AssemblyID { get; set; }
        public int FixtureID { get; set; }
    
        public virtual Assembly Assembly { get; set; }
        public virtual Assembly Assembly1 { get; set; }
        public virtual Fixture Fixture { get; set; }
    }
}
