//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssemblyTypeAtAssembly
    {
        public int Assembly_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> AssemblyTypeID { get; set; }
        public Nullable<int> AssemblyType_ID { get; set; }
        public string AssemblyType { get; set; }
    }
}
