//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MANAGER
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AXIS_AutomationEntitiesBOM : DbContext
    {
        public AXIS_AutomationEntitiesBOM()
            : base("name=AXIS_AutomationEntitiesBOM")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryAtFixture> CategoryAtFixtures { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ParameterAtCategoryAtFixture> ParameterAtCategoryAtFixtures { get; set; }
        public virtual DbSet<FixtureApplicationType> FixtureApplicationTypes { get; set; }
        public virtual DbSet<FixtureDirectionality> FixtureDirectionalities { get; set; }
        public virtual DbSet<FilterBehavior> FilterBehaviors { get; set; }
        public virtual DbSet<FilterType> FilterTypes { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
        public virtual DbSet<ProductTemplate> ProductTemplates { get; set; }
        public virtual DbSet<DependableQuantity> DependableQuantities { get; set; }
        public virtual DbSet<AssemblyTypeAtAssembly> AssemblyTypeAtAssemblies { get; set; }
        public virtual DbSet<PartTypeAtPart> PartTypeAtParts { get; set; }
        public virtual DbSet<AssemblyView> AssemblyViews { get; set; }
        public virtual DbSet<BOM> BOMs { get; set; }
        public virtual DbSet<PartView> PartViews { get; set; }
        public virtual DbSet<Assembly> Assemblies { get; set; }
        public virtual DbSet<AssemblyAtAssembly> AssemblyAtAssemblies { get; set; }
        public virtual DbSet<AvailableAssemblyType> AvailableAssemblyTypes { get; set; }
        public virtual DbSet<AvailablePartType> AvailablePartTypes { get; set; }
        public virtual DbSet<PartAtAssembly> PartAtAssemblies { get; set; }
        public virtual DbSet<Fixture> Fixtures { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<PartRulesFilter> PartRulesFilters { get; set; }
        public virtual DbSet<RenamingExpression> RenamingExpressions { get; set; }
    }
}
