//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssemblyView
    {
        public int T1_AssAtAssembly_ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int AssemblyID { get; set; }
        public int FixtureID { get; set; }
        public Nullable<int> T4_FixtureCode_ID { get; set; }
        public string Code { get; set; }
        public Nullable<int> T2_Assembly_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> AssemblyTypeID { get; set; }
        public Nullable<int> T3_AssemblyType_ID { get; set; }
        public string AssemblyType { get; set; }
    }
}
