//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM
    {
        public int AssyAtAssembly_ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int AssemblyID { get; set; }
        public int FixtureID { get; set; }
        public Nullable<int> PartAtAssembly_ID { get; set; }
        public Nullable<int> PartRefID { get; set; }
        public Nullable<int> AssRefID { get; set; }
        public Nullable<int> FixRefID { get; set; }
        public Nullable<int> id { get; set; }
        public string Name { get; set; }
        public Nullable<int> AssemblyTypeID { get; set; }
        public Nullable<int> AssyType_ID { get; set; }
        public string AssemblyType { get; set; }
        public Nullable<int> Parts_ID { get; set; }
        public string PartName { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Description { get; set; }
        public Nullable<int> PartsType_ID { get; set; }
        public string PartType { get; set; }
        public Nullable<int> Fixtures_ID { get; set; }
        public string Code { get; set; }
        public Nullable<int> FixFamilyID { get; set; }
    }
}
