//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM
    {
        public int AssembliesID { get; set; }
        public string AssemblyName { get; set; }
        public Nullable<int> AssemblyTypeID { get; set; }
        public Nullable<int> PartAtAssemblyID { get; set; }
        public Nullable<int> PartID { get; set; }
        public Nullable<int> AssemblyID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> AssyTypeID { get; set; }
        public string AssemblyTypeName { get; set; }
        public Nullable<int> PartsID { get; set; }
        public string PartName { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Description { get; set; }
        public Nullable<int> PartsTypeID { get; set; }
        public string PartTypeName { get; set; }
    }
}
