//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryAtFixtureView
    {
        public Nullable<int> id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> FixtureId { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public int Category_ID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
    }
}
