//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryAtFixture
    {
        public int id { get; set; }
        public int CategoryId { get; set; }
        public int FixtureId { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsOptionalOverride { get; set; }
        public string FootnoteOverride { get; set; }
        public bool IsMultiselectOverride { get; set; }
        public bool IsObsolete { get; set; }
        public Nullable<int> DefaultFallbackSelection { get; set; }
    
        public virtual Fixture Fixture { get; set; }
        public virtual Category Category { get; set; }
    }
}
