//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fixture()
        {
            this.CategoryAtFixtures = new HashSet<CategoryAtFixture>();
            this.AssemblyAtAssemblies = new HashSet<AssemblyAtAssembly>();
        }
    
        public int id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string FamilyName { get; set; }
        public bool IsDWEnabled { get; set; }
        public int ApplicationTypeId { get; set; }
        public int DirectionalityId { get; set; }
        public bool HasSingleEmmiter { get; set; }
        public int DWGouverningProjectId { get; set; }
    
        public virtual FixtureApplicationType FixtureApplicationType { get; set; }
        public virtual FixtureDirectionality FixtureDirectionality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryAtFixture> CategoryAtFixtures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssemblyAtAssembly> AssemblyAtAssemblies { get; set; }
    }
}
