//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterAtCategoryAtFixtureView
    {
        public Nullable<int> id { get; set; }
        public string Code { get; set; }
        public Nullable<int> CatAtFixture_ID { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> FixtureId { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public int ParAtCatAtFix_ID { get; set; }
        public int CategoryAtFixtureId { get; set; }
        public int ParameterId { get; set; }
        public int DisplayOrder_Id { get; set; }
        public Nullable<int> Parameter_ID { get; set; }
        public string ParameterCode { get; set; }
        public string Description { get; set; }
        public int Category_ID { get; set; }
        public string Name { get; set; }
    }
}
