//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Part()
        {
            this.PartAtAssemblies = new HashSet<PartAtAssembly>();
        }
    
        public int id { get; set; }
        public string PartName { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Description { get; set; }
        public Nullable<int> FixFamilyID { get; set; }
    
        public virtual FamilyName FamilyName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartAtAssembly> PartAtAssemblies { get; set; }
        public virtual PartType PartType { get; set; }
    }
}
