//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartView
    {
        public int id { get; set; }
        public int PartRefID { get; set; }
        public int AssRefID { get; set; }
        public int FixtureID { get; set; }
        public int PART_ID { get; set; }
        public string PartName { get; set; }
        public int TypeID { get; set; }
        public int TYPE_ID { get; set; }
        public string PartType { get; set; }
        public int ASSEMBLY_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> AssemblyTypeID { get; set; }
        public int FIXTURE_ID { get; set; }
        public string Code { get; set; }
    }
}
