//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartAtAssembly
    {
        public int id { get; set; }
        public int PartRefID { get; set; }
        public int AssRefID { get; set; }
    
        public virtual Assembly Assembly { get; set; }
        public virtual Part Part { get; set; }
    }
}
