//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartTypeAtPart
    {
        public int Part_ID { get; set; }
        public string PartName { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> PartType_ID { get; set; }
        public string PartType { get; set; }
        public Nullable<int> FixFamilyID { get; set; }
        public string Description { get; set; }
        public Nullable<int> FamilyName_ID { get; set; }
        public string FamilyName { get; set; }
        public Nullable<int> FixtureFamilyId { get; set; }
    }
}
