//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_CLASS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryAtFixture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryAtFixture()
        {
            this.ParameterAtCategoryAtFixtures = new HashSet<ParameterAtCategoryAtFixture>();
        }
    
        public int id { get; set; }
        public int CategoryId { get; set; }
        public int FixtureId { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsOptionalOverride { get; set; }
        public string FootnoteOverride { get; set; }
        public bool IsMultiselectOverride { get; set; }
        public bool IsObsolete { get; set; }
        public Nullable<int> DefaultFallbackSelection { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ParameterAtCategoryAtFixture ParameterAtCategoryAtFixture { get; set; }
        public virtual Fixture Fixture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParameterAtCategoryAtFixture> ParameterAtCategoryAtFixtures { get; set; }
    }
}
