//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_CLASS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterAtCategoryAtFixture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParameterAtCategoryAtFixture()
        {
            this.CategoryAtFixtures = new HashSet<CategoryAtFixture>();
        }
    
        public int id { get; set; }
        public int CategoryAtFixtureId { get; set; }
        public int ParameterId { get; set; }
        public int DisplayOrder { get; set; }
        public string FootnoteOverride { get; set; }
        public bool IsObsolete { get; set; }
        public string DescriptionOverride { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryAtFixture> CategoryAtFixtures { get; set; }
        public virtual CategoryAtFixture CategoryAtFixture { get; set; }
        public virtual Parameter Parameter { get; set; }
    }
}
