//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_CLASS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartRulesFilter
    {
        public int id { get; set; }
        public Nullable<int> PartID { get; set; }
        public Nullable<int> AssemblyID { get; set; }
        public int ProductID { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string ParameterID { get; set; }
        public string ParameterName { get; set; }
        public int FilterTypeID { get; set; }
        public int OrderOfExecution { get; set; }
        public string PACAF_ID { get; set; }
        public Nullable<int> FilterBehaviorID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> DependabilityID { get; set; }
        public Nullable<int> RenamingExpressionID { get; set; }
    
        public virtual Dependability Dependability { get; set; }
        public virtual FilterBehavior FilterBehavior { get; set; }
        public virtual FilterType FilterType { get; set; }
        public virtual Part Part { get; set; }
        public virtual Assembly Assembly { get; set; }
        public virtual RenamingExpression RenamingExpression { get; set; }
    }
}
