//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_CLASS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTemplate
    {
        public int FixtureId { get; set; }
        public string FixtureCode { get; set; }
        public bool FixtureIsDWEnabled { get; set; }
        public string FixtureDescription { get; set; }
        public string FixtureFamilyName { get; set; }
        public string FixtureApplicationType { get; set; }
        public string FixtureDirectionality { get; set; }
        public Nullable<int> CAF_Id { get; set; }
        public Nullable<int> CAF_CategoryId { get; set; }
        public Nullable<int> CAF_FixtureId { get; set; }
        public Nullable<int> CAF_DisplayOrder { get; set; }
        public Nullable<bool> CAF_IsOptionalOverride { get; set; }
        public Nullable<bool> CAF_IsMultiselectOverride { get; set; }
        public string CAF_FootnoteOverride { get; set; }
        public Nullable<int> ParserFallbackParameterID { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryType { get; set; }
        public Nullable<bool> CategoryIsMultiselect { get; set; }
        public Nullable<bool> CategoryIsOptional { get; set; }
        public string CategoryFootnote { get; set; }
        public Nullable<bool> CategoryIsObsolete { get; set; }
        public Nullable<int> PAC_Id { get; set; }
        public Nullable<int> PAC_CategoryAtFixtureId { get; set; }
        public Nullable<int> PAC_ParameterId { get; set; }
        public Nullable<int> PAC_DisplayOrder { get; set; }
        public string PAC_FootnoteOverride { get; set; }
        public Nullable<int> ParameterId { get; set; }
        public string ParameterCode { get; set; }
        public string ParameterDescription { get; set; }
        public string ParameterFootnote { get; set; }
        public Nullable<bool> ParameterIsObsolete { get; set; }
        public Nullable<int> RVO_Id { get; set; }
        public Nullable<int> RVO_PAC_Id { get; set; }
        public string RVO_ValueExtractRegex { get; set; }
        public string RVO_ValueReAssemblyString { get; set; }
        public string ParameterDescriptionOverride { get; set; }
    }
}
